### ISSUE TITLE
docker not resolving installed npm module

### ISSUE THREAD

**Issue by meligatt** [tipresias/tipresias#78]
- situation: when installing a new npm module (for example styled-components) it is impossible for docker to resolve the package, resulting in throwing an error for frontend service and can't compile.

- what I have to do to fix it: "docker-compose down"  but with this I have to run R, seed db again, etc..etc..
 
resources:
- https://www.jonathan-petitcolas.com/2017/01/26/yarn-npm-install-within-docker-container.html

**Comment by cfranklin11** [comment]
Resolved as a side effect of #81
